<?php
  require_once('view/upper.php');
  require_once('lib/printList.php');
  ?>
</ol>
<?php
  require_once('view/manupulate.php');
  require_once('lib/printContent.php');
  require_once('view/bottom.php');
  ?>
